[package]
name = "jellyfin-matrix-bot"
version = "0.1.0"
authors = ["sparky8251 <sparky@possumlodge.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1 # better optimizations
lto = true # better optimizations

[dependencies]
ruma-client = { git = "https://github.com/ruma/ruma-client" }
url = "2.1"
directories = "2.0"
log = "0.4"
pretty_env_logger = "0.4"
futures = "0.3"
ron = "0.5"
lazy_static = "1.4"
anyhow = "1.0"
uom = "0.27"
nom = "5.1"
rand = "0.7"

[dependencies.tokio]
version = "0.2"
features = ["signal", "macros"]

[dependencies.serde]
version = "1.0"
features = ["derive"]